name: Deploy dev

on:
  workflow_run:
    workflows: ["Run Build"]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to dev
        if: github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success'  # ビルド成功時のみ実行
        run: echo "Deploy to dev"  # (仮)デプロイコマンド
