name: Run Build

on:
  pull_request:
    branches:
      - 'feature/**'
    types: [opened, synchronize]

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and Push Docker Image
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          IMAGE_TAG=$(echo $BRANCH_NAME | tr '/' '-')
          echo "docker build -t myrepo/app:$IMAGE_TAG ."
          echo "docker push myrepo/app:$IMAGE_TAG"


#name: Run Tests
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#    types: [ closed, opened ]
#
#jobs:
#  pr-open:
#    if: github.event.pull_request.opened == true
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Use Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '20'
#      - run: npm ci
#      - run: npm run build
#
#  pr-merge-test:
#    if: github.event.pull_request.merged == true
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v4
#      - name: Use Node.js
#        uses: actions/setup-node@v3
#        with:
#          node-version: '20'
#      - run: npm ci
#      - run: npm run build
#      - run: npm run test
#      - name: GitHub Pages Deploy
#        uses: peaceiris/actions-gh-pages@v4
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          publish_dir: ./dist
#
#  test:
#    runs-on: ubuntu-latest
#
#    steps:
#    - uses: actions/checkout@v4
#    - name: Use Node.js
#      uses: actions/setup-node@v3
#      with:
#        node-version: '20'
#    - run: npm ci
#    - run: npm run build --if-present
#    - run: npm run test
#    - run: npm run deploy
